services:
  - type: web
    name: hotel-motel-eclipse-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd hotel_backend && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd hotel_backend && gunicorn hotel_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
    healthCheckPath: /api/
