# Generated by Django 5.1.2 on 2025-08-20 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_rooms', models.IntegerField(verbose_name='Total de habitaciones')),
                ('occupied_rooms', models.IntegerField(verbose_name='Habitaciones ocupadas')),
                ('available_rooms', models.IntegerField(verbose_name='Habitaciones disponibles')),
                ('cleaning_rooms', models.IntegerField(verbose_name='Habitaciones en limpieza')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingresos totales')),
                ('total_reservations', models.IntegerField(verbose_name='Total de reservaciones')),
                ('occupancy_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de ocupación (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte Diario',
                'verbose_name_plural': 'Reportes Diarios',
                'ordering': ['-date'],
            },
        ),
    ]
