# Generated by Django 5.1.2 on 2025-08-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('receptionist', 'Recepcionista')], default='receptionist', max_length=20, verbose_name='Rol'),
        ),
    ]
