# Generated by Django 5.1.2 on 2025-08-20 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('standard', 'Estándar'), ('love_machine', 'Con Máquina del Amor'), ('suite', 'Suite')], max_length=50, unique=True, verbose_name='Tipo de habitación')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('base_price_5h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base 5h')),
                ('icon', models.CharField(default='🏠', max_length=50, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Número de habitación')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('cleaning', 'En Limpieza'), ('maintenance', 'Mantenimiento')], default='available', max_length=20, verbose_name='Estado')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Piso')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Tipo de habitación')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['number'],
            },
        ),
    ]
