# Generated by Django 5.1.2 on 2025-08-30 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['numero'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='notes',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_type',
            new_name='tipo_habitacion',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='base_price_5h',
        ),
        migrations.AddField(
            model_name='room',
            name='cobro_adicional',
            field=models.BooleanField(default=True, verbose_name='Cobrar horas adicionales'),
        ),
        migrations.AddField(
            model_name='room',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='room',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En Limpieza'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='room',
            name='horas_base',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Horas base incluidas'),
        ),
        migrations.AddField(
            model_name='room',
            name='piso',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='room',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=10, verbose_name='Precio base'),
        ),
        migrations.AddField(
            model_name='room',
            name='precio_hora_adicional',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Precio por hora adicional'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10, verbose_name='Precio base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='precio_hora_adicional',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Precio por hora adicional'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('standard', 'Estándar'), ('love_machine', 'Con Máquina del Amor'), ('suite', 'Suite'), ('ejecutiva', 'Suite Ejecutiva')], max_length=50, unique=True, verbose_name='Tipo de habitación'),
        ),
    ]
