# Generated by Django 5.1.2 on 2025-08-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options_rename_notes_room_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo de habitación'),
        ),
    ]
